### DISCUSSION TITLE
Docker-compose

### DISCUSSION THREAD

**Discussion by Koliera** [advplyr/audiobookshelf#164] [General]
Sorry if a silly question but would it be possible to add to the install guides a docker-compose option since it's easy to use portainer.

**Comment by p1xelll** [comment]
You can use this:
```
audiobookshelf:
  image: zv0n/audiobookshelf:v1.5.5
  container_name: audiobookshelf
  ports:
    - "1337:443"
  volumes:
    - /path/to/audiobooks:/audiobooks
    - /path/to/config:/config
    - /path/to/metadata:/metadata
  restart: unless-stopped
```
