### DISCUSSION TITLE
Caddy setup

### DISCUSSION THREAD

**Discussion by organicnz** [advplyr/audiobookshelf#1897] [Q&A]
Hey folks,

Could you please help with the Caddy setup? I can't obtain a certificate for some reason. Should I add a web socket configuration to the Caddyfile? :)

Thank you :)

OS: Ubuntu 23.04
Cloud: Timeweb
DNS provider: Cloudflare (disabled proxying)
Accessible on: http://178.130.131.149:13378

```
version: "3.7"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - ./audiobooks:/audiobooks
      - ./metadata:/metadata
      - ./config:/config
    restart: unless-stopped
    mem_limit: "2g"
    mem_reservation: "2g"
    cpus: 2
    cpuset: "0"
    networks:
      - no-zero-trust-cloudflared

networks:
  web:
    external: true
    name: web
  no-zero-trust-cloudflared:
    external: false
    driver: bridge
    name: no-zero-trust-cloudflared

volumes:
  caddy_data:
    external: true
      #  caddy:
      #    external: true
  caddy_config:
```

```
x-deploy: &default-deploy
  restart_policy:
    condition: unless-stopped
    delay: 5s
    window: 120s
  update_config:
    order: start-first

version: "3.9"

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
      - ./tls:/etc/caddy/tls
    mem_limit: "2g"
    mem_reservation: "2g"
    cpus: 2
    cpuset: "0"
    networks:
      - no-zero-trust-cloudflared
      - web
        #      - appsmith
    deploy:
      <<: *default-deploy
      update_config:
        order: stop-first
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      
        max-file: "3"      

networks:
  web:
    external: true
    name: web
  no-zero-trust-cloudflared:
    external: false
    driver: bridge
    name: no-zero-trust-cloudflared

volumes:
  caddy_data:
    external: true
  caddy:
    external: true
  caddy_config:
  tls:
    external: true
  vault-data:
    external: true
```

$ cat caddy_config/Caddyfile
```
audiobookshelf.foodshare.club {
  encode zstd gzip

  reverse_proxy audiobookshelf:13378
}

www.audiobookshelf.foodshare.club {
  redir https://audiobookshelf.foodshare.club{uri}
}
```

$ docker logs caddy | grep audiobookshelf
```
{"level":"error","ts":1688527298.5553596,"logger":"http.acme_client","msg":"validating authorization","identifier":"www.audiobookshelf.foodshare.club","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]},"order":"https://acme.zerossl.com/v2/DV90/order/1sCJ9o1LRsCFy961pfH6IA","attempt":1,"max_attempts":3}
{"level":"error","ts":1688527298.5553796,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"www.audiobookshelf.foodshare.club","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 0  - "}
{"level":"error","ts":1688527298.5554018,"logger":"tls.obtain","msg":"will retry","error":"[www.audiobookshelf.foodshare.club] Obtain: [www.audiobookshelf.foodshare.club] solving challenge: www.audiobookshelf.foodshare.club: [www.audiobookshelf.foodshare.club] authorization failed: HTTP 0  -  (ca=https://acme.zerossl.com/v2/DV90)","attempt":13,"retrying_in":21600,"elapsed":43314.879010325,"max_duration":2592000}
{"level":"error","ts":1688530546.5099976,"logger":"http.log.error","msg":"dial tcp 172.22.0.2:13378: connect: connection refused","request":{"remote_ip":"89.175.184.250","remote_port":"45050","proto":"HTTP/1.1","method":"HEAD","host":"audiobookshelf.foodshare.club","uri":"/","headers":{"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"],"Accept-Encoding":["gzip, deflate"],"Accept":["*/*"],"Connection":["keep-alive"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"audiobookshelf.foodshare.club"}},"duration":0.002287591,"status":502,"err_id":"vv2dpn3i6","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688531468.1173284,"logger":"http.log.error","msg":"dial tcp: lookup appsmith on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"40.77.167.123","remote_port":"62216","proto":"HTTP/2.0","method":"GET","host":"appsmith.foodshare.club","uri":"/static/media/layout-sorted-clusters.7f6c2c524ba9a5ffac0ac2dc9e0373ac.svg","headers":{"From":["bingbot(at)microsoft.com"],"User-Agent":["Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"appsmith.foodshare.club"}},"duration":0.001251,"status":502,"err_id":"jkfxnhevq","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688534607.3430502,"logger":"http.log.error","msg":"dial tcp: lookup appsmith on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"157.55.39.224","remote_port":"6617","proto":"HTTP/2.0","method":"GET","host":"appsmith.foodshare.club","uri":"/static/media/compressed.e12b706609bcea5af5e2a46954e0afac.svg","headers":{"User-Agent":["Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"From":["bingbot(at)microsoft.com"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"appsmith.foodshare.club"}},"duration":0.00133937,"status":502,"err_id":"dnvnmrdkz","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688541641.9227529,"logger":"http.log.error","msg":"dial tcp: lookup appsmith on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"207.46.13.218","remote_port":"34028","proto":"HTTP/2.0","method":"GET","host":"appsmith.foodshare.club","uri":"/static/media/executeJs.c2b1701fb3b57e45a70276ac2a1d191f.svg","headers":{"User-Agent":["Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"From":["bingbot(at)microsoft.com"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"appsmith.foodshare.club"}},"duration":0.00150351,"status":502,"err_id":"640d2m6tp","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542122.2506168,"logger":"http.log.error","msg":"dial tcp: lookup appsmith on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"207.46.13.218","remote_port":"33077","proto":"HTTP/2.0","method":"GET","host":"appsmith.foodshare.club","uri":"/static/media/folder-shared.8db35e92c8a201c10e7d6ed3edfdfcb9.svg","headers":{"Accept-Encoding":["gzip, deflate"],"From":["bingbot(at)microsoft.com"],"User-Agent":["Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"Accept":["*/*"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"appsmith.foodshare.club"}},"duration":0.001258591,"status":502,"err_id":"z8dmwcwq0","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542166.6925983,"logger":"http.log.error","msg":"dial tcp: lookup appsmith on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"157.55.39.224","remote_port":"6914","proto":"HTTP/2.0","method":"GET","host":"appsmith.foodshare.club","uri":"/static/media/list.3218767e3c0a4596e317e9b6d8031985.svg","headers":{"Accept-Encoding":["gzip, deflate"],"From":["bingbot(at)microsoft.com"],"User-Agent":["Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36"],"Cache-Control":["no-cache"],"Pragma":["no-cache"],"Accept":["*/*"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"appsmith.foodshare.club"}},"duration":0.001037381,"status":502,"err_id":"uiwihfugd","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542210.0700247,"logger":"http.log.error","msg":"dial tcp 172.22.0.2:13378: connect: connection refused","request":{"remote_ip":"172.22.0.1","remote_port":"34698","proto":"HTTP/2.0","method":"GET","host":"audiobookshelf.foodshare.club","uri":"/","headers":{"Cache-Control":["max-age=0"],"Sec-Fetch-Site":["none"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Dest":["document"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":[],"Sec-Ch-Ua":["\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""],"Dnt":["1"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Accept-Encoding":["gzip, deflate, br"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"audiobookshelf.foodshare.club"}},"duration":0.001342281,"status":502,"err_id":"g7a30u976","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542211.5912325,"logger":"http.log.error","msg":"dial tcp 172.22.0.2:13378: connect: connection refused","request":{"remote_ip":"172.22.0.1","remote_port":"34698","proto":"HTTP/2.0","method":"GET","host":"audiobookshelf.foodshare.club","uri":"/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Sec-Ch-Ua":["\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-User":["?1"],"Sec-Ch-Ua-Platform":["\"macOS\""],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":[],"Cache-Control":["max-age=0"],"Sec-Fetch-Site":["none"],"Sec-Fetch-Mode":["navigate"],"Sec-Ch-Ua-Mobile":["?0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Sec-Fetch-Dest":["document"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"audiobookshelf.foodshare.club"}},"duration":0.00064245,"status":502,"err_id":"dzbt2e4mg","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542212.5714374,"logger":"http.log.error","msg":"dial tcp 172.22.0.2:13378: connect: connection refused","request":{"remote_ip":"172.22.0.1","remote_port":"34698","proto":"HTTP/2.0","method":"GET","host":"audiobookshelf.foodshare.club","uri":"/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""],"Sec-Ch-Ua-Platform":["\"macOS\""],"Dnt":["1"],"Sec-Fetch-Site":["none"],"Sec-Fetch-Dest":["document"],"Upgrade-Insecure-Requests":["1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Sec-Fetch-Mode":["navigate"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"],"Sec-Fetch-User":["?1"],"Cookie":[]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"audiobookshelf.foodshare.club"}},"duration":0.0007544,"status":502,"err_id":"2cekner43","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542526.3259723,"logger":"http.log.error","msg":"dial tcp 172.22.0.2:13378: connect: connection refused","request":{"remote_ip":"64.222.84.197","remote_port":"34102","proto":"HTTP/1.1","method":"GET","host":"audiobookshelf.foodshare.club","uri":"/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-Mode":["navigate"],"Connection":["close"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Sec-Fetch-Dest":["document"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Language":["en-US,en;q=0.9"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"","server_name":"audiobookshelf.foodshare.club"}},"duration":0.000634181,"status":502,"err_id":"hd0wgwcfx","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
{"level":"error","ts":1688542605.8581743,"logger":"http.log.error","msg":"dial tcp: lookup appsmith on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"52.149.22.87","remote_port":"48320","proto":"HTTP/1.1","method":"GET","host":"appsmith.foodshare.club","uri":"/static/media/folder-shared.8db35e92c8a201c10e7d6ed3edfdfcb9.svg","headers":{"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edge/96.0.1054.34"],"Connection":["Keep-Alive"]},"tls":{"resumed":false,"version":771,"cipher_suite":49195,"proto":"","server_name":"appsmith.foodshare.club"}},"duration":0.001186531,"status":502,"err_id":"b3fjxa842","err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"}
```
