### DISCUSSION TITLE
Volume mounting issue. What am I doing wrong?

### DISCUSSION THREAD

**Discussion by hsb-tonmoy** [advplyr/audiobookshelf#2247] [Q&A]
This is my docker-compose.yml:

```
version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /config:/config
      - /metadata:/metadata
      - Z:\Books:/audiobooks
```

My Z drive has a structure like this: `Z:\Books\Neil deGrasse Tyson\Astrophysics for People in a Hurry\audiobook.mp3`

But when I try to add a library and map that folder, I get this:

![image](https://github.com/advplyr/audiobookshelf/assets/35843150/6bc3f8c9-607a-4c56-8299-807eda9546a2)
****
