### DISCUSSION TITLE
Author Images Disappear After Docker Restart in Audiobookshelf v2.17.2

### DISCUSSION THREAD

**Discussion by vawaver** [advplyr/audiobookshelf#3640] [Q&A] [answered]
I am using Audiobookshelf v2.17.2 with the Docker installation. I noticed an issue with author images:

1. I add images to authors in the UI.
2. The images display correctly while the Docker container is running.
3. After restarting the Docker container, the author images no longer appear, and only a placeholder remains.

![autors](https://github.com/user-attachments/assets/0f216899-e9f9-4d08-ba85-3635f92bea55)

**Expected Behavior:**
Author images should persist after restarting the Docker container.

**Actual Behavior:**
Author images are not displayed after a restart, leaving a placeholder image instead.

**Steps to Reproduce:**
1. Run Audiobookshelf v2.17.2 using Docker.
2. Add an image to an author in the UI.
3. Restart the Docker container.
5. Observe that the author images are missing after the restart.

**Environment:**
- Audiobookshelf version: v2.17.2
- Installation method: Docker
- Host OS: Ubuntu 24.04

If more details or logs are required, let me know.

**Comment by nichwall** [comment]
Do you have the `/metadata` directory mapped in your docker compose? You can also try clearing the cache in the server settings.

**Reply by vawaver** [reply]
Uff.. I am affrad I have not. :disappointed: 
Here is my `docker-compose.yml`

```
# version: '3.8'

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"         # Port pre webové rozhranie
    environment:
      - TZ=Europe/Bratislava # Nastavenie časovej zóny
      - ABS_MEDIA_ROOT=/media # Koreňová cesta k médiám
    volumes:
      - /home/tony/audiobookshelf/config:/config      # Konfiguračné súbory
      - /home/tony/Media-files/audiobooks:/audiobooks      # Cesta na mediálne súbory
      - /home/tony/audiobookshelf/transcode:/transcode # Skladisko pre transkódovanie
```      
Be so kind and help me what line of code is missing. I am not IT pro.
Cheers.

**Reply by nichwall** [reply, marked as answer]
You just need to add a `/metadata` mount to your volumes section, such as below:

I'm not sure what the `ABS_MEDIA_ROOT` is that you have, that is not used by the docker container.

```
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"         # Port pre webové rozhranie
    environment:
      - TZ=Europe/Bratislava # Nastavenie časovej zóny
    volumes:
      - /home/tony/audiobookshelf/config:/config      # Konfiguračné súbory
      - /home/tony/audiobookshelf/metadata:/metadata   # <--- Just add this
      - /home/tony/Media-files/audiobooks:/audiobooks      # Cesta na mediálne súbory
      - /home/tony/audiobookshelf/transcode:/transcode # Skladisko pre transkódovanie
```
