### DISCUSSION TITLE
OAuth Sign-in Error: "The OAuth client was not found" when authenticating with Google

### DISCUSSION THREAD

**Discussion by organicnz** [advplyr/audiobookshelf#4117] [Q&A]
Hi folks,
I'm encountering an authentication error when trying to sign in to the application using Google. Here are the details:

Error Details

```
Error message: "Access blocked: Authorization Error"
Error code: 401 (invalid_client)
Specific error: "The OAuth client was not found"
Email account used: [example@gmail.com](mailto:example@gmail.com)
```

Docker compose file

```
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:13378
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./metadata:/metadata
      - ./config:/config
    restart: always
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
      - PORT=13378
      - GOOGLE_OAUTH_CLIENT_ID=370204xxxxxsgnnr.apps.googleusercontent.com
      - GOOGLE_OAUTH_CLIENT_SECRET=GOCSPX-kjvyxxxxx
      - GOOGLE_OAUTH_REDIRECT_URI=https://audiobookshelf.example.com/auth/google/callback
    mem_limit: "14g"
    mem_reservation: "14g"
    cpus: 4
    cpuset: "0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
#    network_mode: host
    networks:
      - no-zero-trust-cloudflared  
      - web
networks:
  web:
    external: true
    name: web  
  no-zero-trust-cloudflared:
    external: false
    driver: bridge
    name: no-zero-trust-cloudflared
  zero-trust-cloudflared:
    external: true
    name: zero-trust-cloudflared

volumes:
  caddy_data:
    external: true
  caddy:
    external: true
  caddy_config:
```

Steps I've Taken

Attempted to sign in using Google authentication
Received the error message described above
Tried clearing browser cache/cookies with the same result

Browser/Environment Information

Browser: Arc
Operating System: macOS/ Android/ iOS
Device Type: web/mobile

Could this be a configuration issue with the OAuth client settings? I'd appreciate any guidance on how to resolve this so I can access the application.

Thank you for your help!
