### DISCUSSION TITLE
xHE-AAC support (Discussion for issue #4236)

### DISCUSSION THREAD

**Discussion by Vito0912** [advplyr/audiobookshelf#4258] [General]
I start this discussion to avoid filling the original issue with extra messages. This is a place to report possible problems with ffmpeg 7.1 using fdk-aac, or with ffprobe 7.1 in general.  

Issue: https://github.com/advplyr/audiobookshelf/issues/4236

# Current Workaround
---
If you need xHE-AAC support (required for some files in [Libation](https://github.com/rmcrackan/Libation/issues/1228)), you can use a custom Dockerfile based on [dymk’s work](https://github.com/dymk). This version adds a setting for the `AUDIOBOOKSHELF_TAG` (ABS tag). **Note:** The build process will take some time.

### Steps

**1. Download the Dockerfile**

Make sure you are in your `docker-compose` folder, then run:

```sh
curl -o Dockerfile "https://gist.githubusercontent.com/Vito0912/55851304c3dc271dbfc3961a628fd495/raw/128338f7fa303cbcbe395b05a97eb5f2907162d7/Dockerfile"
```
or

```sh
wget -O Dockerfile "https://gist.githubusercontent.com/Vito0912/55851304c3dc271dbfc3961a628fd495/raw/128338f7fa303cbcbe395b05a97eb5f2907162d7/Dockerfile"
```

*Please check the downloaded file to ensure it looks correct.*

---

**2. Update your `docker-compose.yml`**

- **Remove** the `image:` line from your service definition.
- **Add** the following `build:` section:

```yaml
build:
  context: .
  dockerfile: Dockerfile
  args:
    AUDIOBOOKSHELF_TAG: ${AUDIOBOOKSHELF_TAG_VAR:-latest}
```

You can set `AUDIOBOOKSHELF_TAG` to a specific version (e.g., `2.21.0`), `edge`, or leave it as `latest` (the default).

---

**3. Build and Run**

```sh
docker compose up -d
```

To update when a new ABS version is released, run:

```sh
docker compose build
docker compose up -d
```

> **Note:**  
> `docker compose pull` will no longer update the image with this setup, since you are building locally.

---

### Additional Notes

- I have not tested playback with xHE-AAC files, as I do not have any. The build process completes successfully, and [dymk](https://github.com/dymk) reports that his builds seemed to work. So I assume it will also work for this.

*Distributing an ffmpeg build with fdk-aac may violate licensing terms. Sharing a pre-built image could be problematic.* - So that's why I do not provide a finsihed image

> The license of libfdk_aac is not compatible with GPL, so the GPL does not permit distribution of binaries containing incompatible code when GPL-licensed code is also included. Therefore this encoder have been designated as "non-free", and you cannot download a pre-built ffmpeg that supports it.
Source: https://trac.ffmpeg.org/wiki/Encode/AAC

Make backups. I am not liable if you loose anything. Make sure you have setup mountpoints correctly!

---

**Credit:**  
Thanks to [dymk](https://github.com/dymk) for the original Dockerfile.

---

### Example

<details><summary>Example Compose</summary>
<p>

```yaml
services:
  audiobookshelf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AUDIOBOOKSHELF_TAG: latest

    # ABS runs on port 13378 by default. If you want to change
    # the port, only change the external port, not the internal port
    ports:
      - 13378:80
    volumes:
      # These volumes are needed to keep your library persistent
      # and allow media to be accessed by the ABS server.
      # The path to the left of the colon is the path on your computer,
      # and the path to the right of the colon is where the data is
      # available to ABS in Docker.
      # You can change these media directories or add as many as you want
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      # The metadata directory can be stored anywhere on your computer
      - ./metadata:/metadata
      # The config directory needs to be on the same physical machine
      # you are running ABS on
      - ./config:/config
    restart: unless-stopped
    # You can use the following user directive to run the ABS
    # docker container as a specific user. You will need to change
    # the UID and GID to the correct values for your user.
    # user: 1000:1000
```

</p>
</details>
