### DISCUSSION TITLE
Traefik Setup

### DISCUSSION THREAD

**Discussion by typhooncarr** [advplyr/audiobookshelf#554] [General]
I see that the documentation has changed for Traefik setup and needing CORS to be turned off for the mobile app to work or it will generate an Unknown Error on login. I have found that the following setup for Traefik  will work with CORS enabled.

```

http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 50

http:
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

http:
  middlewares:
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        accessControlMaxAge: 100
        accessControlAllowHeaders: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Origin, Accept
        accessControlAllowOriginList: '*'
        accessControlAllowCredentials: true
        accessControlExposeHeaders: '*, Authorization'
        addVaryHeader: true
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslProxyHeaders: 
          X-Forwarded-Proto: "https"
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: 'allow-from https:example.com'
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), xr-spatial-tracking=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nofollow,noimageindex,noindex,nosnippet,notranslate"
          server: ""
        customRequestHeaders:
          X-Forwarded-Proto: "https"

http:
  middlewares:
    compress:
      compress: {}

http:
  middlewares:
    nofloc:
      headers:
        customResponseHeaders:
          Permissions-Policy: "interest-cohort=()"

```

If this can be confirmed then the Traefik setup documentation can be adjusted.
