### ISSUE TITLE
[Bug]: User account deleted

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#1419]
### Describe the issue

After my NAS accidentally powered off, ABS (running in Docker) rebooted with the user account missing that was listening at the time. 

Can't really see anything in Docker logs, you might have to help me figure out what's going on here - sounds like a DB corruption issue. 

### Steps to reproduce the issue

1. Listen to audiobooks
2. Force kill Docker?
3. Missing user

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by jt196** [comment]
Hey there, pretty simple, docker-compose. 

Been running this for a year or so without any issues. Funnily enough, the same thing happened about 1hr later (accidental power off the NAS) and the same thing happened. User account that was listening to the audiobooks was deleted.

```
version: '3.3'
services:
  audiobookshelf:
    environment:
        - AUDIOBOOKSHELF_UID=1029
        - AUDIOBOOKSHELF_GID=100
    ports:
        - '13378:80'
    volumes:
        - '/volume1/audio/audiobooks:/audiobooks'
        - './config:/config'
        - './metadata:/metadata'
    labels:
      - com.centurylinklabs.watchtower.enable=true
    container_name: audiobookshelf
    image: advplyr/audiobookshelf:latest

```
