### ISSUE TITLE
[Enhancement]: store the books in a cloud

### ISSUE THREAD

**Issue by vsuh** [advplyr/audiobookshelf#1715]
### Describe the feature/enhancement

It would be great to have ability to store some part of collection in some cloud.

**Comment by Weldawadyathink** [comment]
FYI, you can use rclone to mount cloud storage as a local filesystem, and audiobookshelf can use that. It takes some setup, but once it is working, its reasonably reliable. I have had a similar setup running without issue for about a year now.

**Comment by advplyr** [comment]
Can you be more specific?

I think it is up to the user to mount volumes where the books are.

**Comment by Weldawadyathink** [comment]
> I think it is up to the user to mount volumes where the books are.

Yeah, that is what I was referring to. For example with the rclone docker plugin:
```
volumes:
  audiobooks:
    driver: rclone
    driver_opts:
      remote: 'server:path'
      allow_other: 'true'
      vfs_cache_mode: 'full'
      vfs_cacbe_max_size: 2G
      no_modtime: 'true'
```

The idea from discord was to have audiobookshelf use s3 storage directly, not through something like rclone. ABS would put files into s3 itself, then instead of hosting the downloads through the ABS server, the client could download or stream the files directly from s3. It could open up some interesting scenarios like having ABS hosted on a server with relatively poor bandwidth, but still have downloads and streams be super fast because the files are hosted through amazon (or any other cloud provider). It is probably much more work than it is worth, but it would be an interesting feature.
