### ISSUE TITLE
[Bug]:  2.3.2 setting max-old-space-size causes java out of memory on raspberry pi / memory restricted containers. (Workaround)

### ISSUE THREAD

**Issue by CoryM** [advplyr/audiobookshelf#1938]
### Describe the issue

Starting docker container with version 2.3.2 causes immediate container shutdown.   Running on a raspberry pi 4 2Gb model.

docker log shows java oom (out of memory) error.

-- LOG --
`# Fatal javascript OOM in GC during deserialization`

-- DockerCompose.yml --
```
version: "3.7"
services:
  audiobookshelf:
    restart: unless-stopped
    user: 1000:1000
    image: ghcr.io/advplyr/audiobookshelf:2.3.2
    network_mode: "bridge"
    ports:
      - 13378:80
    volumes:
      - /run/media/corym/myhdd/abs/audiobooks:/audiobooks
      - /run/media/corym/myhdd/abs/podcasts:/podcasts
      - /run/media/corym/myhdd/abs/config:/config
      - /run/media/corym/myhdd/abs/metadata:/metadata
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
```

adding 
```
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024 
```
fixes the issue.  It seems to override the environment variable set inside Dockerfile in 2.3.2
also using docker run -e "NODE_OPTIONS=--max-old-space-size=1024" -p 13378:80 docker_audiobookshelf_1

### Steps to reproduce the issue

1. COMPOSE_HTTP_TIMEOUT=120 docker-compose -f audiobookshelf.yml up -d 
2. docker container crashes

### Audiobookshelf version

v2.3.2

### How are you running audiobookshelf?

Docker
