### ISSUE TITLE
[Bug]: Unexpected end of Input

### ISSUE THREAD

**Issue by MichaelRPowell** [advplyr/audiobookshelf#1970]
### Describe the issue

I took down my Audiobookshelf instance using `docker-compose down`. When trying it start again I have a new issue, the output displays:

```
docker-compose up
Starting audiobookshelf ... done
Attaching to audiobookshelf
audiobookshelf    | /server/libs/fsExtra/copy/copy.js:216
audiobookshelf    |         // do not copy if src is a s
audiobookshelf    |
audiobookshelf    |
audiobookshelf    | SyntaxError: Unexpected end of input
audiobookshelf    |     at Object.compileFunction (node:vm:360:18)
audiobookshelf    |     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
audiobookshelf    |     at Module._compile (node:internal/modules/cjs/loader:1162:27)
audiobookshelf    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
audiobookshelf    |     at Module.load (node:internal/modules/cjs/loader:1076:32)
audiobookshelf    |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
audiobookshelf    |     at Module.require (node:internal/modules/cjs/loader:1100:19)
audiobookshelf    |     at require (node:internal/modules/cjs/helpers:108:18)
audiobookshelf    |     at Object.<anonymous> (/server/libs/fsExtra/copy/index.js:5:11)
audiobookshelf    |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
audiobookshelf exited with code 1
```

My docker-compose.yml:

```
version: '3.5'
services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 1234:80
    volumes:
      - /media/Audiobooks:/audiobooks
      - /media/audiobookshelf:/audiobookshelf
      - /media/audiobookshelf/config:/config
      - /media/audiobookshelf/metadata:/metadata
      - /media/audiobookshelf/podcasts:/podcasts

```

I am happy to provide any information or additional logs if they can help identify the problem.

### Steps to reproduce the issue

1. docker-compose up

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker
