### ISSUE TITLE
[Bug]: Container Fails to Start

### ISSUE THREAD

**Issue by iJasonWade** [advplyr/audiobookshelf#2002]
### Describe the issue

After an update to Linux the container will no longer start.

### Linux System:
```
Linux zerocool 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Crash Logs:

```
audiobookshelf    | SyntaxError: Invalid or unexpected token
audiobookshelf    |     at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/loaders:328:18)
audiobookshelf    |     at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/loaders:269:10)
audiobookshelf    |     at loadBuiltinModule (node:internal/modules/cjs/helpers:54:9)
audiobookshelf    |     at Function.Module._load (node:internal/modules/cjs/loader:887:15)
audiobookshelf    |     at Module.require (node:internal/modules/cjs/loader:1100:19)
audiobookshelf    |     at require (node:internal/modules/cjs/helpers:108:18)
audiobookshelf    |     at Object.<anonymous> (/node_modules/nodemailer/lib/shared/index.js:9:13)
audiobookshelf    |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
audiobookshelf    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
audiobookshelf    |     at Module.load (node:internal/modules/cjs/loader:1076:32)
audiobookshelf    | node:dns:230
audiobookshelf    |     stopPerf(this, kPerfHooksDnsLookupServiceContext, { dEtail: { hostname, service } });  }
audiobookshelf    |                                                                                          ^
audiobookshelf    |
audiobookshelf    | SyntaxError: Invalid or unexpected token
audiobookshelf    |     at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/loaders:328:18)
audiobookshelf    |     at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/loaders:269:10)
audiobookshelf    |     at loadBuiltinModule (node:internal/modules/cjs/helpers:54:9)
audiobookshelf    |     at Function.Module._load (node:internal/modules/cjs/loader:887:15)
audiobookshelf    |     at Module.require (node:internal/modules/cjs/loader:1100:19)
audiobookshelf    |     at require (node:internal/modules/cjs/helpers:108:18)
audiobookshelf    |     at Object.<anonymous> (/node_modules/nodemailer/lib/shared/index.js:9:13)
audiobookshelf    |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
audiobookshelf    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
audiobookshelf    |     at Module.load (node:internal/modules/cjs/loader:1076:32)
```

### docker-compose.yml

```
version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /home/jason/mnt/westerndigital/AudioBooks:/audiobooks
      - /home/jason/configs/audiobookshelf-config:/config
      - /home/jason/configs/audiobookshelf-metadata:/metadata
    restart: 'unless-stopped'
```

### Steps to reproduce the issue

1. Install latest updates to Linux
2. Bring docker container up

### Audiobookshelf version

v2.3.3

### How are you running audiobookshelf?

Docker
