### ISSUE TITLE
[Bug]: Library scan does not detect subfolders

### ISSUE THREAD

**Issue by PozoSer** [advplyr/audiobookshelf#2362]
### Describe the issue

Hi. Thanks for the amazing work. 

Since I moved my install to the Docker version of audiobookshelf (advplyr/audiobookshelf) I have been unable to properly scan my library. It will only detect files on the main folder but won't find anything on any subfolder. 

The docker version is running on ubuntu under proxmox and access the library folder via NFS. My docker-compose is very simple:

```
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      - TZ=Europe/XXX
    volumes:
      - /docker/audiobookshelf/data:/config
      - /downloads:/data
```

Before moving to Docker I had Audiobookshelf running directly on bare metal (an LXC container as installed by tteck scripts) and all worked fine. 

I've searched online and have founded some examples: https://www.reddit.com/r/audiobookshelf/comments/12b7hwy/unable_to_find_media_using_docker_in_windows/ but no solution was found. 

### Steps to reproduce the issue

New docker installation.

1. Create new library and point it to the location.
2. Click scan. 
3. It will only find books that are in the main directory. 

### Audiobookshelf version

v2.4.4

### How are you running audiobookshelf?

Docker
