### ISSUE TITLE
[Bug]: Authelia OIDC - Callback Error 500

### ISSUE THREAD

**Issue by undaunt** [advplyr/audiobookshelf#2412]
### Describe the issue

I'm seeing behavior similar to issue 2370 in that my config is almost the same within Authelia and my network is failing on the callback.

![image](https://github.com/advplyr/audiobookshelf/assets/31376520/0d1474cd-13aa-45e4-b5f5-a7d5baefe64b)

However, I'm not getting a password error but instead the following:

```
12/12/2023 11:06:34 PM SyntaxError: Unexpected token e in JSON at position 0
12/12/2023 11:06:34 PM     at JSON.parse (<anonymous>)
12/12/2023 11:06:34 PM     at Client.userinfo (/node_modules/openid-client/lib/client.js:1291:23)
12/12/2023 11:06:34 PM     at runMicrotasks (<anonymous>)
12/12/2023 11:06:34 PM     at processTicksAndRejections (node:internal/process/task_queues:96:5)
12/12/2023 11:06:34 PM     at async /node_modules/openid-client/lib/passport_strategy.js:181:24
```

Authelia:
```
identity_providers:
  oidc:
    hmac_secret: xxxxx
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
     mykey
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1d
    authorize_code_lifespan: 1m
    id_token_lifespan: 1d
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        #- userinfo # Tried with this enabled and disabled
      allowed_origins:
        - https://contoso.com
        - https://abs.contoso.com # I tried adding this one after reading the guide doc, no effect.
    clients:
    - id: audiobookshelf
      description: Audiobookshelf
      secret: '$pbkdf2-sha512$310000$xxxx'
      pre_configured_consent_duration: 3M
      redirect_uris:
        - https://abs.contoso.com/auth/openid/callback 
      scopes:
        - openid
        - profile
        - email
      userinfo_signing_algorithm: RS256
```

ABS is configured as per [the docs](https://www.audiobookshelf.org/guides/oidc_authentication/).

### Steps to reproduce the issue

1. Log in via SSO
2. Authenticate 2 factors to Authelia
3. Receive internal server error on URL, eg: https://abs.contoso.com/auth/openid/callback?code=authelia_ac_xxxxx&scope=openid+profile+email&state=xxxxxxx

### Audiobookshelf version

v2.6.0

### How are you running audiobookshelf?

Docker
