### ISSUE TITLE
[Bug]: Error in v2.8.1

### ISSUE THREAD

**Issue by ameer1234567890** [advplyr/audiobookshelf#2764]
### Describe the issue

I am getting below error with [v2.8.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.1).

```
node:internal/modules/cjs/loader:1456
    throw err;
    ^
SyntaxError: /node_modules/mime-db/db.json: Unterminated string in JSON at position 185882
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1453:39)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/node_modules/mime-db/index.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
Node.js v20.11.1
```

PS: The previous release version still works well for me.

### Steps to reproduce the issue

1. Update to v2.8.1
2. Start container

### Audiobookshelf version

v2.8.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Can you share the logs that led up to that crash?

**Comment by ameer1234567890** [comment]
This is the full log

**Comment by nichwall** [comment]
Looks like one of your json files may be malformed?

**Comment by ameer1234567890** [comment]
It's not my json file. It's a json file in the node_modules directory.

**Comment by advplyr** [comment]
Is there any more information you can share? At this time it's not enough to take any action with

**Comment by ameer1234567890** [comment]
I tried doing a clean docker compose without any bind mounts or volumes, and this is the complete log which I get.

```
node:internal/modules/cjs/loader:1456
    throw err;
    ^
SyntaxError: /node_modules/mime-db/db.json: Unterminated string in JSON at position 185882
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1453:39)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/node_modules/mime-db/index.js:12:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
Node.js v20.11.1
```

**Comment by ameer1234567890** [comment]
I looked into the file being referenced by the error message: `/node_modules/mime-db/db.json` and it seems to be truncated and thus not valid json. The container keeps restarting after the error message and it is in a restart loop.

**Comment by advplyr** [comment]
What path are you using to get the docker image?

**Comment by ameer1234567890** [comment]
This is my compose file:
```
version: "3.7"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.8.0
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /home/pi/Audiobooks:/audiobooks
      - /home/pi/docker/audiobookshelf/metadata:/metadata
      - /home/pi/docker/audiobookshelf/config:/config
    restart: unless-stopped
    environment:
      - user=1000:1000
    healthcheck:
           test: wget --spider http://localhost || exit 1
```

**Comment by nichwall** [comment]
I just tried using a brand new container (no volumes, everything local to the container) and making a new container with a copy of my data. I am not seeing this behavior in either case.

```
version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.8.1
    ports:
      - 13390:80
# with and without following volumes
    volumes:
      - /volume1/docker/audiobookshelf/audiobooks:/audiobooks
      - /volume1/docker/audiobookshelf/podcasts:/podcasts
      - /volume1/docker/audiobookshelf/config:/config
      - /volume1/docker/audiobookshelf/metadata:/metadata
```
