### ISSUE TITLE
[Bug]: ERROR: [Server] attempt to init server when server already has a root user (Server.js:291)

### ISSUE THREAD

**Issue by clifmo** [advplyr/audiobookshelf#2831]
### Describe the issue

I've successfully run audiobookshelf internally for a month now. I finally got around to adding it to my reverse proxy for external access. When setup, I can reach audiobookshelf, but it displays the Initial Server Setup: Create Root User screen. Expected behavior is to present the login form. 

Container logs shows ERROR: [Server] attempt to init server when server already has a root user (Server.js:291). This behavior seems triggered by accessing over a new/different hostname. What can be done to have it work on local and public domains simultaneously?

```yaml
 audiobookshelf:
  image: ghcr.io/advplyr/audiobookshelf
  ports:
   13378:80
  volumes:
    - /var/config:/config
    - /var/metadata:/metadata
    - /mnt/audiobooks:/audiobooks
    - /mnt/podcasts:/podcasts
  ```
  
  ```
  location / {
      proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto $scheme;
      proxy_set_header  Host              $host;
      proxy_set_header Upgrade            $http_upgrade;
      proxy_set_header Connection         "upgrade";
      proxy_http_version                  1.1;
      proxy_redirect                      http:// https://;
      proxy_pass http://<interal-address>:13378;
    }
  ```

### Steps to reproduce the issue

1. Run docker container and access on a local domain name.
2. Add reverse proxy configuration and access on public domain name.
3. external-domain.com/login displays root account setup instead of login form.

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker
