### ISSUE TITLE
[Bug]: Mismatch in Docker documentationfor folder Podcasts <-> podcasts

### ISSUE THREAD

**Issue by XploD-Ing** [advplyr/audiobookshelf#3582]
### What happened?

When installing audiobookshelf according to documentation, it states you have to set
```
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - </path/to/audiobooks>:/audiobooks
      - </path/to/podcasts>:/podcasts
      - </path/to/config>:/config
      - </path/to/metadata>:/metadata
```

This results in damaged podcast libraries when restarting the container.
When you docker exec  into the container, you can see that there are 2 folders: /podcasts and /Podcasts. The later is used for files, the first is the one mapped into the volume

Therefore, the docker compose should state
./podcasts:/Podcasts
or the folder should be renamed to lower case, because all other folders are lower case.

### What did you expect to happen?

One restart, all podcasts should be displayed correctly

### Steps to reproduce the issue

1. Use the docker-compose file to start audiobookshelf
2. Add a bodcast, download one episode
3. docker compose restart
4. All images are gone, folder is declared missing

### Audiobookshelf version

2.16.2

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None
