### ISSUE TITLE
[Bug]: MODULE_NOT_FOUND error in Docker, crashing on startup

### ISSUE THREAD

**Issue by dima-ser** [advplyr/audiobookshelf#4309]
### What happened?

Updated to latest docker image. Container crashing after startup. See logs below

### What did you expect to happen?

I expected it to not crash

### Steps to reproduce the issue

1. Start up the docker container
2. Watch docker container crash

### Audiobookshelf version

2.23.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
node:internal/modules/cjs/loader:1215
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
  code: 'MODULE_NOT_FOUND',
  ^
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
}
  throw err;
    at Module._load (node:internal/modules/cjs/loader:1043:27)
  requireStack: []
Error: Cannot find module '/index.js'
    at node:internal/main/run_main_module:28:49 {
Node.js v20.19.2
```

### Additional Notes

Running on Synology

**Comment by DieselTech** [comment]
Duplicate of https://github.com/advplyr/audiobookshelf/issues/4292

Check that thread for answers. tl;dr - this is a synology issue.

**Comment by DieselTech** [comment]
> Thanks, I did a "Clean" on the project, rebuilt it and now it works. Not sure why.

It works because synology does really weird stuff on their own that isn't part of docker. They were caching environment variables and other parts of the image that shouldn't be cached. Forcing it to create a new container gets around that problem.

**Comment by Dinth** [comment]
Im experiencing the same issue on Debian running on normal baremetal server, defo nothing to do with Synology.
Here is my docker-compose:
```
services:
  audiobookshelf:
    user: "${MEDIA_PUID}:${MEDIA_PGID}"
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - ALL
    container_name: audiobookshelf
    hostname: audiobookshelf
    image: advplyr/audiobookshelf:latest
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - audiobookshelf
      - traefik
    ports:
      - 3378:80/tcp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.${DOMAIN_NAME}`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.audiobookshelf.tls=true"
      - "traefik.http.routers.audiobookshelf.tls.certresolver=letsencrypt"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
    volumes:
      - /Data/Ebooks/Audiobooks:/audiobooks:ro
      - /opt/docker/audiobookshelf/audiobookshelf_config:/config
      - /opt/docker/audiobookshelf/audiobookshelf_metadata:/metadata
      - /Data/Ebooks/Podcasts:/podcasts:ro
    working_dir: /
networks:
  audiobookshelf:
    name: audiobookshelf
    driver: bridge
    external: false
  traefik:
    name: traefik
    external: true
```

And the log repeadly shows:

```
audiobookshelf  | 2025-05-18T20:16:19.902865872Z Error: Cannot find module '/index.js'
audiobookshelf  | 2025-05-18T20:16:19.902871958Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
audiobookshelf  | 2025-05-18T20:16:19.902891324Z     at Module._load (node:internal/modules/cjs/loader:1043:27)
audiobookshelf  | 2025-05-18T20:16:19.902896265Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
audiobookshelf  | 2025-05-18T20:16:19.902900237Z     at node:internal/main/run_main_module:28:49 {
audiobookshelf  | 2025-05-18T20:16:19.902904229Z   code: 'MODULE_NOT_FOUND',
audiobookshelf  | 2025-05-18T20:16:19.902907836Z   requireStack: []
audiobookshelf  | 2025-05-18T20:16:19.902911254Z }
audiobookshelf  | 2025-05-18T20:16:19.902914557Z 
audiobookshelf  | 2025-05-18T20:16:19.902917876Z Node.js v20.19.2
audiobookshelf  | 2025-05-18T20:17:20.339930382Z node:internal/modules/cjs/loader:1215
audiobookshelf  | 2025-05-18T20:17:20.339990002Z   throw err;
audiobookshelf  | 2025-05-18T20:17:20.340003612Z   ^
audiobookshelf  | 2025-05-18T20:17:20.340014340Z 
audiobookshelf  | 2025-05-18T20:17:20.340024516Z Error: Cannot find module '/index.js'
audiobookshelf  | 2025-05-18T20:17:20.340034197Z     at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
audiobookshelf  | 2025-05-18T20:17:20.340043793Z     at Module._load (node:internal/modules/cjs/loader:1043:27)
audiobookshelf  | 2025-05-18T20:17:20.340053408Z     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
audiobookshelf  | 2025-05-18T20:17:20.340063393Z     at node:internal/main/run_main_module:28:49 {
audiobookshelf  | 2025-05-18T20:17:20.340073540Z   code: 'MODULE_NOT_FOUND',
audiobookshelf  | 2025-05-18T20:17:20.340082593Z   requireStack: []
audiobookshelf  | 2025-05-18T20:17:20.340091925Z }
audiobookshelf  | 2025-05-18T20:17:20.340100837Z 
audiobookshelf  | 2025-05-18T20:17:20.340109179Z Node.js v20.19.2
```

it was working fine until an update a few days ago (maybe up to two weeks ago). Completely destroying the stack and redeploying the compose file still doesnt work
