### ISSUE TITLE
[Enhancement]: add proxy setting for podcast downloading

### ISSUE THREAD

**Issue by rockonedege** [advplyr/audiobookshelf#4396]
### Type of Enhancement

None

### Describe the Feature/Enhancement

it would be nice to set a http(s) proxy for podcast  downloading, esp.  when ABS is hosted behind a firewall.

### Why would this be helpful?

to subscribe and automatically download episodes from behind a fire-walled environment, like corporate LAN. 

### Future Implementation (Screenshot)

![Image](https://github.com/user-attachments/assets/1a874916-679b-4654-828a-c10ecff0f7af)

### Audiobookshelf Server Version

v2.24.0

**Comment by Vito0912** [comment]
See https://www.audiobookshelf.org/docs#network

**Comment by rockonedege** [comment]
I am not sure about how to use EXP_PROXY_SUPPORT
- set an http proxy uri, or
- set TRUE and then set the actual proxy to environment  variable http_proxy ?

**Comment by rockonedege** [comment]
here's my docker compose file trying to use a proxy
```yaml
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: "audiobookshelf"
    environment:
      - AUDIOBOOKSHELF_UID=1026
      - AUDIOBOOKSHELF_GID=100
      - http_proxy=http://192.168.3.10:2080
      - https_proxy=http://192.168.3.10:2080
      - no_proxy=localhost,127.0.0.1,192.168.3.10
    restart: always
...
```

it did not work.

I have not try 'EXP_PROXY_SUPPORT' as I am not sure how to use it yet.

**Comment by nichwall** [comment]
You can just add it as an environment variable. 

```yaml
audiobookshelf:
  image: advplyr/audiobookshelf:latest
  container_name: "audiobookshelf"
  environment:
    - http_proxy=http://192.168.3.10:2080
    - https_proxy=http://192.168.3.10:2080
    - no_proxy=localhost,127.0.0.1,192.168.3.10
    - EXP_PROXY_SUPPORT=1
  restart: always
...
```

Also `AUDIOBOOKSHELF_UID` and `AUDIOBOOKSHELF_GID` no longer do anything.
