### ISSUE TITLE
[Bug]: After library rescan, audiobookshelf shows issue (item directory is missing)

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#474]
### Describe the issue

From time to time I made a rescan of my library (normal). After this rescan, audiobookshelf shows me issues (left hand side)
![grafik](https://user-images.githubusercontent.com/15927779/164418175-8584546a-254c-4ca4-85f7-f1db0cf7f833.png)

I checked the file location but I don't find any missing file (album complete)

If I make a re-scan, the issue goes away.
![grafik](https://user-images.githubusercontent.com/15927779/164418561-9287f763-a439-43cb-a7c6-5b46b681fdd2.png)

I have that problem since the beginning.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

1.7.2 and 2.0.0

### How are you running audiobookshelf?

Docker

**Comment by szemlicka** [comment]
Hi, some more info.
Looks like a normal library re-scan doesn't end correct.

Here the outbut from log:
```
[2022-04-21T16:10:20.605Z]  INFO: [Scanner] Library scan lscan_q6cttcy0wumyhfuadk completed in 7:31.0 | 1 Added | 12 Updated | 14 Missing           
[2022-04-21T16:10:20.607Z]  INFO: [LibraryController] Scan complete    
```
But the dashboard showing "Scanning Main"

In additional to this, if I try to rescan a single album to remove the issue, the rescan process doesn't start. I d not see anything in the logfile and the issue still exists. 
In 1.72 was this function ok and the issue about missing file/directory  goes away.

**Comment by VGITC** [comment]
Similar issue in v2.0.14 (Unraid Docker)

- All working normally
- Did a library scan (from settings->Libraries->"selected library"->scan
- 41 books were marked as "Item directory is missing" (interestingly 40 from the same series and one from another series, other series and books were unaffected)
- Checked Edit->Files -> Full Path is correct -> confirmed by terminal command -> stat "pasted full path"
- a re-scan of the library did not correct
- a re-scan from the 3 dot menu on the file(s) did not correct (debug log does not show anything occurred"
- a re-scan from the "edit" menu of the files(s) did correct (debug log shows found and library updated)
- did this for all 41 and all returned to normal

**Comment by Everett115** [comment]
I am having the same issue. When I click on the book it says what parts are missing. When I check, they do exist in the file directory and they show up in the "library files" section on the AudioBookShelf page. Some books had this issue from the start and more had the same problem after a force re-scan.

**Comment by Everett115** [comment]
I just figured out the issue but I'm not sure why it occurs. When I click on the "manage tracks" button I see that the files arent ordered properly. When I manually edit them the problem is fixed. I double-checked the naming and track metadata and they were correct so for some reason AudioBookShelf is putting them in the wrong order and then thinks files are missing. [Here is a screenshot that shows the issue.](https://i.postimg.cc/HxJM3gbz/Capture.jpg). In the screenshot, you can see that the server sees the proper track number from the metadata and filename but for some reason has assigned them in the wrong order. Rescanning does not fix, I had to manually reorder the tracks in AudioBookServer. [Here is a link to my daily log in case anyone wants to figure out why this issue is occuring](https://drive.google.com/file/d/1zT9ttIlAZFnEDomB5YVad-Z5syWRQnbq/view?usp=sharing).

**Comment by advplyr** [comment]
Can you give steps to reproduce this? It will probably require showing what your directory structure looks like.

**Comment by danielnbalasoiu** [comment]
This bug is still there (`v2.2.14`):

<details>
    <summary>docker-compose.yaml</summary>

```yaml
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13378:80
    volumes:
      - ../../_volumes/audiobookshelf/audiobooks:/data/audiobooks
      - ../../_volumes/audiobookshelf/books:/data/books
      - ../../_volumes/audiobookshelf/podcasts:/data/podcasts
      - ../../_volumes/audiobookshelf/config:/config
      - ../../_volumes/audiobookshelf/metadata:/metadata
```

</details>

<details>
  <summary>Screenshots</summary>
I don't know if the backslash `\` is the reason, but this doesn't seem right to me 🤔

![image](https://user-images.githubusercontent.com/46020698/216761589-de883ae6-e1d4-4158-b15d-53b6a615cf50.png)
![image](https://user-images.githubusercontent.com/46020698/216761609-0eeae00d-a6b4-4321-8efa-a5ad7168c389.png)
![image](https://user-images.githubusercontent.com/46020698/216761641-89b0ac73-edd7-450e-8b89-6ebdc5bc1e40.png)

</details>

**Comment by advplyr** [comment]
It could be the backslash. It should be checking for backslash and replacing it if on windows. Are you running docker on windows?

**Comment by danielnbalasoiu** [comment]
No. Forgot to mention. I'm on Ubuntu 22.04.1 LTS

**Comment by advplyr** [comment]
When you are re-importing your OPML file are there podcasts in that OPML file that are already on your server?

**Comment by danielnbalasoiu** [comment]
No. No podcast in the library

**Comment by danielnbalasoiu** [comment]
Here is a snippet from the OPML file I'm using to import podcasts.

```opml
<?xml version="1.0"?>
<opml version="1.0">
  <head>
    <title>Podcast Subscriptions</title>
  </head>
  <body>
    <outline type="rss" text="2.5 Admins" title="2.5 Admins" xmlUrl="https://2.5admins.com/feed/podcast" htmlUrl="https://2.5admins.com"/>
    <outline type="rss" text="99% Invisible" title="99% Invisible" xmlUrl="https://feeds.simplecast.com/BqbsxVfO" htmlUrl="https://99percentinvisible.org"/>
    <outline type="rss" text="A Death In Cryptoland" title="A Death In Cryptoland" xmlUrl="https://www.cbc.ca/podcasting/includes/adeathincryptoland.xml" htmlUrl="www.cbc.ca/podcasts"/>
  </body>
</opml>
```

**Comment by advplyr** [comment]
I just uploaded that as an OPML file and it worked for me.

The backslash does need to be updated so it doesn't cause other issues down the line, but it is not the reason for this. This must be something with your file system. Have you checked the docker logs?

![image](https://user-images.githubusercontent.com/67830747/216774310-1aeb90b6-b78e-49b2-9f3f-b1a865b7de5d.png)

**Comment by danielnbalasoiu** [comment]
Can you post your `docker-compose.yaml` file please?

**Comment by advplyr** [comment]
I don't use docker-compose but you can refer to the one in the docs. You can also check the docker logs that will have errors in there about the item not being found.

**Comment by danielnbalasoiu** [comment]
I have just tested in my home directory
```yaml
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=99
      - AUDIOBOOKSHELF_GID=100
    ports:
      - 13379:80
    volumes:
      - ./audiobookshelf/data/audiobooks:/data/audiobooks
      - ./audiobookshelf/data/books:/data/books
      - ./audiobookshelf/data/podcasts:/data/podcasts
      - ./audiobookshelf/config/config:/config
      - ./audiobookshelf/config/metadata:/metadata
      - ./audiobookshelf/backups:/metadata/backups
```

and imported the sample OPML file:
![image](https://user-images.githubusercontent.com/46020698/216774752-2076a796-7e74-4d09-b196-80783fbefa52.png)
