### ISSUE TITLE
[Bug]: docker audiobookshelf image 2.1.4 can't start with error code 243

### ISSUE THREAD

**Issue by DuckieNukeEm** [advplyr/audiobookshelf#966]
### Describe the issue

I've updated the docker images for audiobookshelf from 2.0.18 to 2.1.14, and ran "docker compose up", it spins up, then every second it returns a "Exited with error code 243", I had to downgrade the docker image back to 2.0.18 in order to resume using the docker image. Below is my compose file used for docker image 2.1.14:

```
version: '2.5.0'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.1.14
    user: "${UID}:${GID}"
    ports:
      - "80:80"
    volumes:
      - "/usr/share/audiobookshelf/audiobooks:/audiobooks"
      - "/usr/share/audiobookshelf/config:/config"
      - "/usr/share/audiobookshelf/metadata:/metadata"
      - "/usr/share/audiobookshelf/podcasts:/podcasts"
    restart: unless-stopped
```
Here is the output from ```docker version```

>  Client: Docker Engine - Community
>  Version:           20.10.16
>  API version:       1.41
>  Go version:        go1.17.10
>  Git commit:        aa7e414
>  Built:             Thu May 12 09:17:28 2022
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.16
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.17.10
>   Git commit:       f756502
>   Built:            Thu May 12 09:15:33 2022
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.4
>   GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
>  runc:
>   Version:          1.1.1
>   GitCommit:        v1.1.1-0-g52de29d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

output from ```docker compose version```
> Docker Compose version v2.5.0

output of ```lsb_release -a```

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.6 LTS
> Release:	18.04
> Codename:	bionic

### Steps to reproduce the issue

1.  create ```docker-compose.yml``` file as describe above
2. run ```docker compose up```

### Audiobookshelf version

2.1.14

### How are you running audiobookshelf?

Docker
